### ISSUE TITLE
Issue with your category on Library Manager

### ISSUE THREAD

**Issue by 00alis** [daitangio/sid-arduino-lib#2]
Hi!
On https://create.arduino.cc/editor (the Arduino Web IDE) we include all the libraries in the Library Manager, your library is giving a warning for every single compilation, and some users have complained about it on our Forum.
`WARNING: Category '' in library StereoSID is not valid. Setting to 'Uncategorized'`

From what I see everything is correct in your libraries.properties and you correctly made a release after updating the file. Any idea on why the compiler might be giving this warning?

Thanks a lot!

**Comment by daitangio** [comment]
Changed category and pushed a new tag version. Hope it helps
